apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/products(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: product-service-w08e1
            port:
              number: 8000
      - path: /api/orders(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: order-service-w08e1
            port:
              number: 8001
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-w08e1
            port:
              number: 80